name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew :manager:assembleDebug
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: manager/build/outputs/apk/debug/
